### ISSUE TITLE
Player attack animation and physics

### ISSUE THREAD

**Issue by Mohido** [Mohido/Ragnarok_Madness_Game#25]
Player must have an attack move which MUST looks coooool. Make also include its physics (Depends on the weapon). Create a weapon Class as well, It can be an Item interface implemention.  Make a weapon animation, slash sound, and finally physics (Item usage() ) function can do the magic :).

**Comment by RealGorandos** [comment]
I will take this issue. Moreover, I think the priority must be for the player's collision with the surrounding objects so that Shuaa can start working on its test cases!

**Comment by Mohido** [comment]
Sounds like a plan. Handle player collisions and if you can fix the biased diagonal motion as well on the way. 
Equation for that can be:
dirx = dirx / sqrt (dirx*dirx + diry*diry)
diry = diry / sqrt (dirx*dirx + diry*diry)

**Comment by RealGorandos** [comment]
### **Reporting the updates!**

This issue is partly done. The remaining is the player's attack!

**The physics that were added:-**
_A function which detects if the player is colliding with object and it returns boolean. Moreover, I enhanced it by making the player able to slide while colliding._

**The physics that were fixed:-**
_The player's diagonal motion was faster than the horizontal and vertical motion. Hence, I solved this problem and normalized them._

**The physics that are yet to be done:-**
_The player's attacking animation!_

**Comment by Mohido** [comment]
Good job on what you did so far. The collision works fine according to what @Shuaa11 tested. Keep up with this issue and finalize the player when you have time.

**Comment by Mohido** [comment]
I came to help in completing this issue. I edited the animation code a bit. Player Class is now a bit neater. I still have not pull request the features yet.

**Comment by Mohido** [comment]
Implemented the basics of the bullets animations, as well as, the attack physics and player physics. Therefore, I am closing this issue and we can open more specific issues related to specific features. This issue is very general indeed.
